/* =========================================================
   MANJEET DIGITAL HUB - COMPLETE APP.JS
   Version: 4.8
   Smart Digital Tools. Simple Solutions.
   ========================================================= */

"use strict";

document.addEventListener("DOMContentLoaded", function () {
  const modal=document.getElementById("toolModal"),modalOverlay=document.getElementById("modalOverlay"),closeTool=document.getElementById("closeTool"),modalTitle=document.getElementById("modalTitle"),modalIcon=document.getElementById("modalIcon"),toolContent=document.getElementById("toolContent"),searchInput=document.getElementById("toolSearch"),noResults=document.getElementById("noResults"),currentYear=document.getElementById("currentYear");
  if(currentYear)currentYear.textContent=new Date().getFullYear();

  const toolData={
    aienhancer:{title:"Smart Photo Enhancer",icon:"✨"},fillandsign:{title:"Document Fill & Sign",icon:"✍️"},photosignature:{title:"Photo + Signature Maker",icon:"📸"},applicationwriter:{title:"Smart Application Writer",icon:"📝"},
    idprint:{title:"ID Card Print",icon:"🪪"},idsheet:{title:"ID Card Print Sheet",icon:"🪪"},pvcautocrop:{title:"PVC Auto Crop",icon:"✂️"},passport:{title:"Passport Photo Maker",icon:"🪪"},photocropresize:{title:"Photo Crop And Resize",icon:"📐"},resume:{title:"Resume Maker",icon:"📄"},bgremover:{title:"BG Remover",icon:"🪄"},
    compressor:{title:"Image Compressor",icon:"🗜️"},resizer:{title:"Image Resizer",icon:"↔️"},converter:{title:"Image Converter",icon:"🔄"},reducer:{title:"Photo Size Reducer",icon:"📉"},social:{title:"Social Media Resizer",icon:"📱"},
    jpgpdf:{title:"JPG → PDF",icon:"🖼️"},pngpdf:{title:"PNG → PDF",icon:"📄"},pdf:{title:"Images → PDF",icon:"📄"},mergepdf:{title:"Merge PDF",icon:"📚"},splitpdf:{title:"Split PDF",icon:"✂️"},pdfjpg:{title:"PDF → JPG",icon:"🖼️"},pdfpng:{title:"PDF → PNG",icon:"🖼️"},pdfcompressor:{title:"PDF Compressor",icon:"🗜️"},pdfextractor:{title:"PDF Page Extractor",icon:"📤"},pdfreorder:{title:"PDF Page Reorder",icon:"🔀"},pdfrotate:{title:"PDF Rotate",icon:"🔄"},pdfprint:{title:"PDF Print Sheet",icon:"🖨️"},
    schoolid:{title:"School ID Card Maker",icon:"🎓"},employeeid:{title:"Employee ID Card Maker",icon:"💼"},marriagebio:{title:"Marriage Biodata Maker",icon:"💍"},photosheet:{title:"A4 Photo Sheet Maker",icon:"🖨️"},document:{title:"Document Photo Maker",icon:"📑"},visiting:{title:"Visiting Card Maker",icon:"💳"},certificate:{title:"Certificate Maker",icon:"🏆"},signature:{title:"Signature Maker",icon:"✍️"},photolayout:{title:"Photo Print Layout",icon:"📐"},label:{title:"Label / Sticker Maker",icon:"🏷️"},
    emi:{title:"EMI Calculator",icon:"₹"},gst:{title:"GST Calculator",icon:"%"},percentage:{title:"Percentage Calculator",icon:"%"},sip:{title:"SIP Calculator",icon:"📈"},fd:{title:"FD Calculator",icon:"🏦"},rd:{title:"RD Calculator",icon:"🏦"},loaninterest:{title:"Loan Interest Calculator",icon:"💰"},interest:{title:"Simple Interest Calculator",icon:"➕"},compound:{title:"Compound Interest Calculator",icon:"📊"},discount:{title:"Discount Calculator",icon:"🏷️"},profit:{title:"Profit & Loss Calculator",icon:"📈"},age:{title:"Age Calculator",icon:"🎂"},insurance:{title:"Insurance Policy Return Calculator",icon:"🛡️"},cgpa:{title:"CGPA → Percentage",icon:"🎓"},gpa:{title:"GPA Calculator",icon:"🎓"},marks:{title:"Marks Required Calculator",icon:"📝"},grade:{title:"Grade Calculator",icon:"🏅"},studytime:{title:"Study Time Calculator",icon:"⏱️"},mocktest:{title:"Mock Test",icon:"🧠"}
  };

  function escapeHTML(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
  function formatNumber(v,d=2){const n=Number(v);return Number.isFinite(n)?n.toLocaleString("en-IN",{maximumFractionDigits:d}):"0";}
  function formatKB(b){return(b/1024).toFixed(1)+" KB";}
  function downloadBlob(blob,filename){if(!blob){alert("Unable to create file.");return;}const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function loadImage(file){return new Promise((resolve,reject)=>{if(!file)return reject(new Error("No file selected"));const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(u);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error("Image load failed"))};img.src=u;});}
  function canvasToBlob(c,t="image/jpeg",q=.9){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error("Unable to create image")),t,q));}
  function createButton(t,c=""){return `<button type="button" class="mdh-action ${c}">${escapeHTML(t)}</button>`;}
  function createFileInput(a="image/*",m=false){return `<label class="mdh-upload-box"><input type="file" class="mdh-file-input" accept="${escapeHTML(a)}" ${m?"multiple":""}><div class="mdh-upload-icon">📁</div><strong>Choose File${m?"s":""}</strong><small>Tap here to select from your device</small></label>`;}
  function toolCSS(){return `<style>.mdh-tool{display:flex;flex-direction:column;gap:10px}.mdh-tool h3{margin:0;font-size:16px}.mdh-tool p{margin:0;color:#64748b;font-size:12px}.mdh-field{display:flex;flex-direction:column;gap:4px}.mdh-field label{font-size:11px;font-weight:600}.mdh-field input,.mdh-field select,.mdh-field textarea{width:100%;box-sizing:border-box;border:1px solid #dbe3ef;border-radius:8px;padding:7px 9px;font-size:12px;background:#fff}.mdh-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.mdh-grid-3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.mdh-upload-box{position:relative;display:block;width:100%;box-sizing:border-box;border:2px dashed #bfdbfe;border-radius:12px;padding:15px 10px;text-align:center;background:#f8fbff;cursor:pointer}.mdh-upload-box input{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important}.mdh-upload-icon{font-size:25px;margin-bottom:5px}.mdh-upload-box strong{display:block;font-size:12px}.mdh-upload-box small{display:block;margin-top:4px;color:#64748b;font-size:10px}.mdh-action{border:0;border-radius:8px;padding:8px 10px;background:#2563eb;color:#fff;font-size:12px;font-weight:600;cursor:pointer;min-height:36px}.mdh-action.secondary{background:#eef4ff;color:#1d4ed8}.mdh-result{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px}.mdh-stat{padding:8px;border-radius:8px;background:#eff6ff;text-align:center}.mdh-stat span{display:block;color:#64748b;font-size:10px}.mdh-stat strong{display:block;margin-top:3px;font-size:13px}.mdh-note{font-size:10px;color:#64748b;background:#f8fafc;padding:8px;border-radius:8px}.mdh-coming{text-align:center;padding:15px 8px}.mdh-coming .big{font-size:35px}.mdh-error{color:#dc2626;background:#fef2f2;border-radius:8px;padding:8px;font-size:11px}</style>`;}

  function openTool(t){
    const routes={
      aienhancer:"tools/smart-photo-enhancer.html",fillandsign:"tools/document-fill-sign.html",photosignature:"tools/photo-signature-maker.html",applicationwriter:"tools/smart-application-writer.html",
      pngpdf:"tools/png-to-pdf.html",pdfjpg:"tools/pdf-to-jpg.html",pdfpng:"tools/pdf-to-png.html",splitpdf:"tools/split-pdf.html",pdfcompressor:"tools/pdf-compressor.html",pdfextractor:"tools/pdf-page-extractor.html",jpgpdf:"tools/jpg-to-pdf.html",pvcautocrop:"tools/pvc-auto-crop.html",bgremover:"tools/bg-remover.html",photocropresize:"tools/photo-crop-resize.html",schoolid:"tools/school-id-card-maker.html",passport:"tools/passport-photo-maker.html",employeeid:"tools/employee-id-card-maker.html",marriagebio:"tools/marriage-biodata-maker.html",document:"tools/document-scanner.html",visiting:"tools/visiting-card-maker.html",resume:"tools/resume-maker.html",certificate:"tools/certificate-maker.html",signature:"tools/signature-maker.html",idprint:"tools/id-card-print.html",idsheet:"tools/id-card-print-sheet.html",label:"tools/label-sticker-maker.html",emi:"tools/emi-calculator.html",gst:"tools/gst-calculator.html",sip:"tools/sip-calculator.html"
    };
    if(routes[t]){window.location.href=routes[t];return;}
    const data=toolData[t];if(!data){showComingSoon("Digital Tool");return;}
    if(modalTitle)modalTitle.textContent=data.title;if(modalIcon)modalIcon.textContent=data.icon;if(modal){modal.classList.add("active");modal.setAttribute("aria-hidden","false");}document.body.classList.add("modal-open");loadTool(t);
  }
  function closeModal(){if(modal){modal.classList.remove("active");modal.setAttribute("aria-hidden","true");}document.body.classList.remove("modal-open");if(toolContent)toolContent.innerHTML="";}
  if(closeTool)closeTool.addEventListener("click",closeModal);if(modalOverlay)modalOverlay.addEventListener("click",closeModal);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal();});
  document.querySelectorAll(".tool-card").forEach(c=>c.addEventListener("click",()=>{const t=c.getAttribute("data-tool");if(t)openTool(t);}));
  if(searchInput)searchInput.addEventListener("input",function(){const q=this.value.trim().toLowerCase();let v=0;document.querySelectorAll(".tool-card").forEach(c=>{const n=(c.getAttribute("data-name")||c.textContent||"").toLowerCase();if(!q||n.includes(q)){c.style.display="";v++;}else c.style.display="none";});if(noResults)noResults.classList.toggle("show",q.length>0&&v===0);});
  function showComingSoon(t){if(toolContent)toolContent.innerHTML=toolCSS()+`<div class="mdh-coming"><div class="big">🚀</div><h3>${escapeHTML(t)}</h3><p>This tool is coming soon to Manjeet Digital Hub.</p></div>`;}

  function loadCompressor(){toolContent.innerHTML=toolCSS()+`<div class="mdh-tool"><h3>🗜️ Image Compressor</h3><p>Reduce image file size while keeping good quality.</p>${createFileInput()}<div class="mdh-field"><label>Quality: <span id="qualityValue">80</span>%</label><input type="range" id="compressQuality" min="10" max="100" value="80"></div><div id="compressResult"></div></div>`;const input=toolContent.querySelector(".mdh-file-input"),quality=document.getElementById("compressQuality"),qv=document.getElementById("qualityValue"),result=document.getElementById("compressResult");quality.oninput=function(){qv.textContent=this.value};input.onchange=async function(){const f=this.files[0];if(!f)return;try{const img=await loadImage(f),c=document.createElement("canvas");c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext("2d").drawImage(img,0,0);const blob=await canvasToBlob(c,"image/jpeg",Number(quality.value)/100),saved=Math.max(0,Math.round((1-blob.size/f.size)*100));result.innerHTML=`<div class="mdh-grid-3"><div class="mdh-stat"><span>Original</span><strong>${formatKB(f.size)}</strong></div><div class="mdh-stat"><span>New Size</span><strong>${formatKB(blob.size)}</strong></div><div class="mdh-stat"><span>Saved</span><strong>${saved}%</strong></div></div><br>${createButton("⬇ Download Compressed Image")}`;result.querySelector("button").onclick=()=>downloadBlob(blob,"manjeet-compressed.jpg");}catch(e){result.innerHTML='<div class="mdh-error">Unable to process this image.</div>';}};}
  function loadResizer(){toolContent.innerHTML=toolCSS()+`<div class="mdh-tool"><h3>↔️ Image Resizer</h3>${createFileInput()}<div class="mdh-grid"><div class="mdh-field"><label>Width</label><input type="number" id="resizeWidth"></div><div class="mdh-field"><label>Height</label><input type="number" id="resizeHeight"></div></div><label><input type="checkbox" id="keepRatio" checked> Keep aspect ratio</label><div id="resizeResult"></div></div>`;const i=toolContent.querySelector(".mdh-file-input"),w=document.getElementById("resizeWidth"),h=document.getElementById("resizeHeight"),k=document.getElementById("keepRatio"),r=document.getElementById("resizeResult");let im=null,ratio=1;i.onchange=async function(){if(!this.files[0])return;im=await loadImage(this.files[0]);w.value=im.naturalWidth;h.value=im.naturalHeight;ratio=im.naturalWidth/im.naturalHeight};w.oninput=function(){if(k.checked&&im&&this.value)h.value=Math.round(Number(this.value)/ratio)};h.oninput=function(){if(k.checked&&im&&this.value)w.value=Math.round(Number(this.value)*ratio)};const b=document.createElement("button");b.className="mdh-action";b.textContent="Resize & Download";r.appendChild(b);b.onclick=async()=>{if(!im)return alert("Please select an image first.");const W=+w.value,H=+h.value,c=document.createElement("canvas");c.width=W;c.height=H;c.getContext("2d").drawImage(im,0,0,W,H);downloadBlob(await canvasToBlob(c),"manjeet-resized.jpg")};}
  function loadConverter(){toolContent.innerHTML=toolCSS()+`<div class="mdh-tool"><h3>🔄 Image Converter</h3>${createFileInput()}<div class="mdh-field"><label>Output Format</label><select id="convertFormat"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></div><div id="convertResult"></div></div>`;const i=toolContent.querySelector(".mdh-file-input"),f=document.getElementById("convertFormat"),r=document.getElementById("convertResult");i.onchange=async function(){if(!this.files[0])return;const im=await loadImage(this.files[0]),c=document.createElement("canvas");c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext("2d");if(f.value==="image/jpeg"){x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height)}x.drawImage(im,0,0);const blob=await canvasToBlob(c,f.value,.92),ext=f.value==="image/png"?"png":f.value==="image/webp"?"webp":"jpg";r.innerHTML=createButton("⬇ Download Converted Image");r.querySelector("button").onclick=()=>downloadBlob(blob,`manjeet-converted.${ext}`)};}
  function loadReducer(){showComingSoon("Photo Size Reducer");}
  function loadSocial(){showComingSoon("Social Media Resizer");}
  function loadImagesToPDF(){toolContent.innerHTML=toolCSS()+`<div class="mdh-tool"><h3>📄 Images → PDF</h3><p>Select one or more images and save them as PDF.</p>${createFileInput("image/*",true)}<div id="pdfResult"></div></div>`;const i=toolContent.querySelector(".mdh-file-input"),r=document.getElementById("pdfResult");i.onchange=function(){const fs=Array.from(this.files);if(!fs.length)return;r.innerHTML=`<div class="mdh-result"><strong>${fs.length} image${fs.length>1?"s":""} selected</strong><br><br>${createButton("🖨️ Create / Save PDF")}</div>`;r.querySelector("button").onclick=()=>printImagesAsPDF(fs)};}
  function printImagesAsPDF(fs){const w=window.open("","_blank","width=900,height=700");if(!w)return alert("Please allow pop-ups to create PDF.");let h=`<!doctype html><html><head><style>@page{size:A4;margin:0}body{margin:0}.page{width:210mm;height:297mm;display:flex;align-items:center;justify-content:center;page-break-after:always}.page img{max-width:190mm;max-height:277mm;object-fit:contain}</style></head><body>`;fs.forEach(f=>h+=`<div class="page"><img src="${URL.createObjectURL(f)}"></div>`);h+="</body></html>";w.document.write(h);w.document.close();w.onload=()=>setTimeout(()=>w.print(),700);}
  function simpleCalc(t,h,fn){toolContent.innerHTML=toolCSS()+`<div class="mdh-tool"><h3>${t}</h3>${h}${createButton("Calculate")}<div id="calcResult"></div></div>`;toolContent.querySelector("button").onclick=fn;}
  function val(id){return Number(document.getElementById(id).value)}
  function loadEMI(){simpleCalc("₹ EMI Calculator",`<div class="mdh-field"><label>Loan Amount (₹)</label><input type="number" id="p" value="500000"></div><div class="mdh-field"><label>Annual Interest Rate (%)</label><input type="number" id="r" value="10"></div><div class="mdh-field"><label>Loan Tenure (Years)</label><input type="number" id="t" value="5"></div>`,()=>{let P=val("p"),n=val("t")*12,r=val("r")/1200,e=r?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n,total=e*n;document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>Monthly EMI ₹${formatNumber(e)} | Total ₹${formatNumber(total)}</strong></div>`});}
  function loadGST(){simpleCalc("% GST Calculator",`<input type="number" id="p" value="10000"><input type="number" id="r" value="18">`,()=>{let a=val("p"),g=a*val("r")/100;document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>GST ₹${formatNumber(g)} | Total ₹${formatNumber(a+g)}</strong></div>`});}
  function loadPercentage(){simpleCalc("% Percentage Calculator",`<input type="number" id="r" value="20"><input type="number" id="p" value="500">`,()=>document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>${val("r")}% of ${val("p")} = ${formatNumber(val("r")*val("p")/100)}</strong></div>`);}
  function loadSimpleInterest(){simpleCalc("➕ Simple Interest Calculator",`<input type="number" id="p" value="100000"><input type="number" id="r" value="8"><input type="number" id="t" value="5">`,()=>{let i=val("p")*val("r")*val("t")/100;document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>Interest ₹${formatNumber(i)} | Total ₹${formatNumber(val("p")+i)}</strong></div>`});}
  function loadCompound(){simpleCalc("📊 Compound Interest Calculator",`<input type="number" id="p" value="100000"><input type="number" id="r" value="8"><input type="number" id="t" value="5">`,()=>{let P=val("p"),A=P*Math.pow(1+val("r")/400,4*val("t"));document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>Interest ₹${formatNumber(A-P)} | Total ₹${formatNumber(A)}</strong></div>`});}
  function loadDiscount(){simpleCalc("🏷️ Discount Calculator",`<input type="number" id="p" value="1000"><input type="number" id="r" value="20">`,()=>{let d=val("p")*val("r")/100;document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>Discount ₹${formatNumber(d)} | Final ₹${formatNumber(val("p")-d)}</strong></div>`});}
  function loadProfit(){simpleCalc("📈 Profit & Loss Calculator",`<input type="number" id="p" value="1000"><input type="number" id="r" value="1200">`,()=>{let d=val("r")-val("p");document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>${d>=0?"Profit":"Loss"}: ₹${formatNumber(Math.abs(d))}</strong></div>`});}
  function loadLoanInterest(){loadSimpleInterest()}
  function loadAge(){toolContent.innerHTML=toolCSS()+`<div class="mdh-tool"><h3>🎂 Age Calculator</h3><input type="date" id="dob">${createButton("Calculate Age")}<div id="ageResult"></div></div>`;toolContent.querySelector("button").onclick=()=>{let v=document.getElementById("dob").value;if(!v)return;let d=new Date(v+"T00:00:00"),t=new Date(),y=t.getFullYear()-d.getFullYear(),m=t.getMonth()-d.getMonth(),day=t.getDate()-d.getDate();if(day<0){m--;day+=new Date(t.getFullYear(),t.getMonth(),0).getDate()}if(m<0){y--;m+=12}document.getElementById("ageResult").innerHTML=`<div class="mdh-result"><strong>${y} Years, ${m} Months, ${day} Days</strong></div>`};}
  function loadCGPA(){simpleCalc("🎓 CGPA → Percentage",`<input type="number" id="p" value="8.5" step=".01">`,()=>document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>Approx. Percentage: ${formatNumber(val("p")*9.5)}%</strong></div>`);}
  function loadGrade(){simpleCalc("🏅 Grade Calculator",`<input type="number" id="p" value="85">`,()=>{let p=val("p"),g=p>=90?"A+":p>=80?"A":p>=70?"B":p>=60?"C":p>=50?"D":"F";document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>Grade: ${g}</strong></div>`});}
  function loadStudyTime(){simpleCalc("⏱️ Study Time Calculator",`<input type="number" id="p" value="6"><input type="number" id="r" value="4">`,()=>document.getElementById("calcResult").innerHTML=`<div class="mdh-result"><strong>${formatNumber(val("r")?val("p")/val("r"):0)} hours per subject</strong></div>`);}

  function loadTool(t){switch(t){
    case"compressor":loadCompressor();break;case"resizer":case"photocropresize":loadResizer();break;case"converter":loadConverter();break;case"reducer":loadReducer();break;case"social":loadSocial();break;case"jpgpdf":case"pngpdf":case"pdf":case"pdfprint":loadImagesToPDF();break;
    case"emi":loadEMI();break;case"gst":loadGST();break;case"percentage":loadPercentage();break;case"loaninterest":loadLoanInterest();break;case"interest":loadSimpleInterest();break;case"compound":loadCompound();break;case"discount":loadDiscount();break;case"profit":loadProfit();break;case"age":loadAge();break;case"cgpa":loadCGPA();break;case"grade":loadGrade();break;case"studytime":loadStudyTime();break;default:showComingSoon(toolData[t]?toolData[t].title:"Digital Tool");
  }}
  document.addEventListener("keydown",function(e){const m=navigator.platform.toUpperCase().indexOf("MAC")>=0?e.metaKey:e.ctrlKey;if(m&&e.key.toLowerCase()==="k"){e.preventDefault();if(searchInput){searchInput.focus();searchInput.select();}}});
  if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));
  console.log("Manjeet Digital Hub v4.8 loaded successfully.");
});
