(function(){"use strict";
function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
ready(function(){
 var cards=[].slice.call(document.querySelectorAll('.tool-card')); if(!cards.length)return;
 var css=document.createElement('style');css.textContent='.mdh-finder{max-width:820px;margin:15px auto 0;padding:13px;border:1px solid #dbeafe;border-radius:16px;background:rgba(255,255,255,.92);box-shadow:0 8px 24px rgba(37,99,235,.08);position:relative;z-index:4}.mdh-finder-row{display:flex;gap:8px}.mdh-finder input{flex:1;min-width:0;border:1px solid #dbe3ee;border-radius:11px;padding:11px 12px;font:inherit;font-size:12px;outline:0}.mdh-finder input:focus{border-color:#60a5fa;box-shadow:0 0 0 3px rgba(37,99,235,.08)}.mdh-find-btn{border:0;border-radius:11px;background:#2563eb;color:#fff;padding:0 14px;font-weight:800;font-size:11px}.mdh-find-results{display:none;margin-top:9px;gap:7px;flex-wrap:wrap}.mdh-find-results.show{display:flex}.mdh-find-chip{border:1px solid #bfdbfe;background:#eff6ff;color:#1d4ed8;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:750;cursor:pointer}.mdh-card-actions{position:absolute;left:6px;right:6px;bottom:6px;display:flex;justify-content:space-between;gap:4px;opacity:0;transition:.18s}.tool-card:hover .mdh-card-actions,.tool-card:focus-within .mdh-card-actions{opacity:1}.mdh-mini{border:1px solid #dbeafe;background:rgba(255,255,255,.95);color:#2563eb;border-radius:8px;padding:4px 6px;font-size:8px;font-weight:800;cursor:pointer}.mdh-help-pop{position:fixed;inset:0;z-index:9999;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(15,23,42,.55)}.mdh-help-pop.show{display:flex}.mdh-help-box{width:min(430px,100%);background:#fff;border-radius:18px;padding:20px;box-shadow:0 25px 70px rgba(15,23,42,.25)}.mdh-help-box h3{margin:0 0 10px;font-size:18px}.mdh-help-box ol{padding-left:20px;color:#475569;font-size:12px;line-height:1.7}.mdh-help-close{width:100%;margin-top:12px;border:0;border-radius:10px;padding:10px;background:#2563eb;color:#fff;font-weight:800}.mdh-launch-links{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.mdh-launch-links a{font-size:10px;color:#cbd5e1;text-decoration:none}.mdh-launch-links a:hover{color:#fff}@media(max-width:650px){.mdh-card-actions{opacity:1}.tool-card{padding-bottom:32px}.mdh-finder-row{flex-direction:column}.mdh-find-btn{min-height:38px}.mdh-finder{margin-top:12px}}';document.head.appendChild(css);
 var hero=document.querySelector('.hero .hero-inner'); if(hero&&!document.getElementById('mdhSmartFinder')){var f=document.createElement('div');f.id='mdhSmartFinder';f.className='mdh-finder';f.innerHTML='<div class="mdh-finder-row"><input id="mdhNeed" type="text" placeholder="What do you want to do? e.g. photo 50 KB, make ID card, calculate EMI"><button class="mdh-find-btn" type="button">Find Tool</button></div><div class="mdh-find-results" id="mdhFindResults"></div>';hero.appendChild(f)}
 function text(c){return ((c.dataset.name||'')+' '+c.textContent).toLowerCase()}
 var aliases={photo:['passport','photocropresize','aienhancer','bgremover','photosignature'],image:['photocropresize','aienhancer','jpgpdf','pngpdf'],kb:['photocropresize','aienhancer'],compress:['pdfcompressor','aienhancer'],pdf:['jpgpdf','pngpdf','pdfjpg','pdfpng','splitpdf','pdfcompressor','pdfextractor','fillandsign'],id:['schoolid','employeeid','idprint','idsheet'],school:['schoolid'],employee:['employeeid'],biodata:['marriagebio'],marriage:['marriagebio'],certificate:['certificate'],resume:['resume'],emi:['emi'],loan:['emi','loaninterest'],gst:['gst'],insurance:['insurance'],signature:['signature','photosignature','fillandsign'],application:['applicationwriter'],background:['bgremover'],crop:['photocropresize','pvcautocrop'],passport:['passport']};
 function find(q){q=q.toLowerCase().trim();if(!q)return[];var ids=[];Object.keys(aliases).forEach(function(k){if(q.indexOf(k)>-1)ids=ids.concat(aliases[k])});var direct=cards.filter(function(c){return q.split(/\s+/).some(function(w){return w.length>2&&text(c).indexOf(w)>-1})}).map(function(c){return c.dataset.tool});ids=ids.concat(direct);return ids.filter(function(v,i,a){return v&&a.indexOf(v)===i}).slice(0,6)}
 function card(id){return cards.find(function(c){return c.dataset.tool===id})}
 function showFind(){var input=document.getElementById('mdhNeed'),out=document.getElementById('mdhFindResults');if(!input||!out)return;var ids=find(input.value);out.innerHTML='';if(!ids.length){out.innerHTML='<span style="font-size:10px;color:#64748b">Try words like PDF, passport photo, ID card, EMI, GST, signature or biodata.</span>';out.classList.add('show');return}ids.forEach(function(id){var c=card(id);if(!c)return;var b=document.createElement('button');b.type='button';b.className='mdh-find-chip';b.textContent=(c.dataset.name||'Open tool');b.onclick=function(){c.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(function(){c.click()},350)};out.appendChild(b)});out.classList.add('show')}
 var findBtn=document.querySelector('.mdh-find-btn'),need=document.getElementById('mdhNeed');if(findBtn)findBtn.onclick=showFind;if(need)need.addEventListener('keydown',function(e){if(e.key==='Enter')showFind()});
 var pop=document.createElement('div');pop.className='mdh-help-pop';pop.id='mdhHelpPop';pop.innerHTML='<div class="mdh-help-box"><h3 id="mdhHelpTitle">How to use</h3><ol id="mdhHelpSteps"></ol><button class="mdh-help-close" type="button">Close</button></div>';document.body.appendChild(pop);pop.querySelector('.mdh-help-close').onclick=function(){pop.classList.remove('show')};pop.onclick=function(e){if(e.target===pop)pop.classList.remove('show')};
 function help(c){var n=c.dataset.name||'this tool',steps=['Open '+n+'.','Choose or enter the required file/details.','Check the preview or result carefully.','Use the available Download, Print or Save option.'];document.getElementById('mdhHelpTitle').textContent='How to use '+n;var ol=document.getElementById('mdhHelpSteps');ol.innerHTML='';steps.forEach(function(s){var li=document.createElement('li');li.textContent=s;ol.appendChild(li)});pop.classList.add('show')}
 function share(c){var name=c.dataset.name||'Manjeet Digital Hub tool',url=location.href.split('#')[0]+'#tools',data={title:name,text:'Try '+name+' on Manjeet Digital Hub',url:url};if(navigator.share){navigator.share(data).catch(function(){})}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(function(){alert('Tool link copied.')})}else{prompt('Copy this link:',url)}}
 cards.forEach(function(c){if(c.querySelector('.mdh-card-actions'))return;var a=document.createElement('div');a.className='mdh-card-actions';a.innerHTML='<button type="button" class="mdh-mini mdh-how">? How</button><button type="button" class="mdh-mini mdh-share">↗ Share</button>';a.querySelector('.mdh-how').onclick=function(e){e.preventDefault();e.stopPropagation();help(c)};a.querySelector('.mdh-share').onclick=function(e){e.preventDefault();e.stopPropagation();share(c)};c.appendChild(a)});
 var foot=document.querySelector('.site-footer .footer-inner');if(foot&&!foot.querySelector('.mdh-launch-links')){var l=document.createElement('div');l.className='mdh-launch-links';l.innerHTML='<a href="./contact.html">Contact & Support</a><a href="./contact.html">Report Problem</a><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a>';foot.appendChild(l)}
});})();