(function(){"use strict";
function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn()}
ready(function(){
 var cards=[].slice.call(document.querySelectorAll('.tool-card')); if(!cards.length)return;
 var css=document.createElement('style');css.textContent='.mdh-card-actions{position:absolute;left:6px;right:6px;bottom:6px;display:flex;justify-content:space-between;gap:4px;opacity:0;transition:.18s}.tool-card:hover .mdh-card-actions,.tool-card:focus-within .mdh-card-actions{opacity:1}.mdh-mini{border:1px solid #dbeafe;background:rgba(255,255,255,.96);color:#2563eb;border-radius:8px;padding:4px 6px;font-size:8px;font-weight:800;cursor:pointer}.mdh-help-pop{position:fixed;inset:0;z-index:9999;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(15,23,42,.55)}.mdh-help-pop.show{display:flex}.mdh-help-box{width:min(430px,100%);background:#fff;border-radius:18px;padding:20px;box-shadow:0 25px 70px rgba(15,23,42,.25)}.mdh-help-box h3{margin:0 0 10px;font-size:18px}.mdh-help-box ol{padding-left:20px;color:#475569;font-size:12px;line-height:1.7}.mdh-help-close{width:100%;margin-top:12px;border:0;border-radius:10px;padding:10px;background:#2563eb;color:#fff;font-weight:800}.mdh-launch-links{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}.mdh-launch-links a{font-size:10px;color:#cbd5e1;text-decoration:none}.mdh-launch-links a:hover{color:#fff}@media(max-width:650px){.mdh-card-actions{opacity:1;left:5px;right:5px;bottom:5px}.tool-card{padding-bottom:31px!important}.mdh-mini{font-size:7.5px;padding:4px 5px}.tool-card h4{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;min-height:23px}.tool-card p{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}';document.head.appendChild(css);
 /* One search experience: reuse the main search box as the smart finder. */
 var search=document.getElementById('toolSearch');if(search){search.placeholder='What do you want to do? e.g. photo 50 KB, ID card, EMI';search.setAttribute('aria-label','Find a digital tool');}
 function text(c){return ((c.dataset.name||'')+' '+c.textContent).toLowerCase()}
 var aliases={photo:['passport','photocropresize','aienhancer','bgremover','photosignature'],image:['photocropresize','aienhancer','jpgpdf','pngpdf'],kb:['photocropresize','aienhancer'],compress:['pdfcompressor','aienhancer'],pdf:['jpgpdf','pngpdf','pdfjpg','pdfpng','splitpdf','pdfcompressor','pdfextractor','fillandsign'],id:['schoolid','employeeid','idprint','idsheet'],school:['schoolid'],employee:['employeeid'],biodata:['marriagebio'],marriage:['marriagebio'],certificate:['certificate'],resume:['resume'],emi:['emi'],loan:['emi','loaninterest'],gst:['gst'],insurance:['insurance'],signature:['signature','photosignature','fillandsign'],application:['applicationwriter'],background:['bgremover'],crop:['photocropresize','pvcautocrop'],passport:['passport']};
 function smartMatch(c,q){if(!q)return true;var words=q.split(/\s+/).filter(function(w){return w.length>1}),hay=text(c);if(words.some(function(w){return hay.indexOf(w)>-1}))return true;var id=c.dataset.tool||'';return Object.keys(aliases).some(function(k){return q.indexOf(k)>-1&&aliases[k].indexOf(id)>-1})}
 if(search){search.addEventListener('input',function(){var q=this.value.toLowerCase().trim();var visible=0;cards.forEach(function(c){var yes=smartMatch(c,q);c.style.display=yes?'':'none';if(yes)visible++});var nr=document.getElementById('noResults');if(nr){nr.hidden=!(q&&visible===0);nr.classList.toggle('show',!!(q&&visible===0))}})}
 var pop=document.createElement('div');pop.className='mdh-help-pop';pop.id='mdhHelpPop';pop.innerHTML='<div class="mdh-help-box"><h3 id="mdhHelpTitle">How to use</h3><ol id="mdhHelpSteps"></ol><button class="mdh-help-close" type="button">Close</button></div>';document.body.appendChild(pop);pop.querySelector('.mdh-help-close').onclick=function(){pop.classList.remove('show')};pop.onclick=function(e){if(e.target===pop)pop.classList.remove('show')};
 function help(c){var n=c.dataset.name||'this tool',steps=['Open '+n+'.','Choose or enter the required file/details.','Check the preview or result carefully.','Use the available Download, Print or Save option.'];document.getElementById('mdhHelpTitle').textContent='How to use '+n;var ol=document.getElementById('mdhHelpSteps');ol.innerHTML='';steps.forEach(function(s){var li=document.createElement('li');li.textContent=s;ol.appendChild(li)});pop.classList.add('show')}
 function share(c){var name=c.dataset.name||'Manjeet Digital Hub tool',url=location.href.split('#')[0]+'#tools',data={title:name,text:'Try '+name+' on Manjeet Digital Hub',url:url};if(navigator.share){navigator.share(data).catch(function(){})}else if(navigator.clipboard){navigator.clipboard.writeText(url).then(function(){alert('Tool link copied.')})}else{prompt('Copy this link:',url)}}
 cards.forEach(function(c){if(c.querySelector('.mdh-card-actions'))return;var a=document.createElement('div');a.className='mdh-card-actions';a.innerHTML='<button type="button" class="mdh-mini mdh-how">? How</button><button type="button" class="mdh-mini mdh-share">↗ Share</button>';a.querySelector('.mdh-how').onclick=function(e){e.preventDefault();e.stopPropagation();help(c)};a.querySelector('.mdh-share').onclick=function(e){e.preventDefault();e.stopPropagation();share(c)};c.appendChild(a)});
 var foot=document.querySelector('.site-footer .footer-inner');if(foot&&!foot.querySelector('.mdh-launch-links')){var l=document.createElement('div');l.className='mdh-launch-links';l.innerHTML='<a href="./contact.html">Contact & Support</a><a href="./contact.html">Report Problem</a><a href="./privacy.html">Privacy</a><a href="./terms.html">Terms</a>';foot.appendChild(l)}
});})();